adding necessary step for clarity
Originally, steps to show how to fill in BrowserStack test details programmatically didn't indicate where the request module came from. This produced the following error:

```js
Error: Cannot find module 'request'
Require stack:
- /.../selenium-test/bstack_google_test.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/.../selenium-test/bstack_google_test.js:2:17)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/.../selenium-test/bstack_google_test.js'
  ]
}
```