Update index.md
> Variable and class declarations are also hoisted, so they too can be referenced before they are declared. Note that doing so can lead to unexpected errors, and is not generally recommended.

While "Variable and class declarations are also hoisted" is true, the sentence that follows, "so they too can be referenced before they are declared" is only true for variables, specifically for `var` declarations (differences with `const` and `let` are discussed later in the document), classes on the other hand, will fail to be referenced. 

The following code will give an error:

```javascript
const catClassRef = Cat;

class Cat {}
```

Error in NodeJS (https://replit.com/@AndresZapata11/Hoisting#index.js):

```bash
ReferenceError: Cannot access 'Cat' before initialization
    at Object.<anonymous> (/home/runner/Hoisting/index.js:1:21)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
```

Error in Chrome (https://nwuyr9.csb.app/):

```bash
Uncaught ReferenceError: Cannot access 'Cat' before initialization
```