refactored code and updated tutorial text to reflect changes (#31050)
* refactored code and updated tutorial text to reflect changes

Refactored code are changes to how module exports are imported and usage of WebDriver's built-in module exports, thus reducing the amount of code needed and providing consistency throughout the [Setting up your own test automation environment](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/Your_own_automation_environment) document.

* refactored code

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* refactored code

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* refactored code

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* refactored code

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* refactored code

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* refactored code

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* refactored code

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* refactored code

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* updated `lambdatest_google_test.js` example for consistency

Removed unnecessary `until` import and refactored how module exports are imported and used.

* updated `bstack_google_test.js` file

Current version on this mdn web docs page looks like it is using outdated code, found on the [Selenium WebDriver capabilities for running tests on BrowserStack.](https://www.browserstack.com/automate/capabilities?tag=selenium-4).  It produces the following error:

```js
/.../selenium-test/node_modules/selenium-webdriver/lib/http.js:618
    throw new error.WebDriverError(value)
          ^

WebDriverError: Authorization required
    at parseHttpResponse (/.../selenium-test/node_modules/selenium-webdriver/lib/http.js:618:11)
    at Executor.execute (/.../selenium-test/node_modules/selenium-webdriver/lib/http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  remoteStacktrace: ''
}
```

* formatted code

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* formatted code

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* formatted code

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* fixed imported WebDriver exports

Co-authored-by: Hamish Willee <hamishwillee@gmail.com>

* Update files/en-us/learn/tools_and_testing/cross_browser_testing/your_own_automation_environment/index.md

* Update files/en-us/learn/tools_and_testing/cross_browser_testing/your_own_automation_environment/index.md

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

* Update index.md

* formatted text and added formatting for consistency

Co-authored-by: Hamish Willee <hamishwillee@gmail.com>

* run prettier

* Remove the other webdriver mentions (not needed as we import specific interfaces

* Since IIFE is a little unusual as syntax goes, add a note on first use

---------

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Co-authored-by: Hamish Willee <hamishwillee@gmail.com>