Update index.md
Hello, I was working through the tutorial and came across some issues with the github portion.
Mainly the following commands:
git remote add origin name-of-repo.git
git push github main

The above yields the following error:
error: src refspec main does not match any
error: failed to push some refs to 'name-of-repo.git'

I tried it twice using two different repos and obtained the same error.
I don't think it matters but I am on linux.
As a result of getting stuck with the procedure above, I decided the run the commands 
suggested by github after creating the empty repo:
git remote add origin name-of-repo.git
git branch -M main
git push -u origin main

As a result I am suggesting we replace the old commands with the above.
I hope that's okay. I tried not to make too many changes to your wording since it is your article after all.

Whatever the case, thanks for the guide. I am finding it to be very useful!