Actions: Escape slashes in issue-regex-labeler.yml (#16204)
This change un-breaks our “Label issues by MDN URL or other regex match
in issue description” GitHub Action — which has been broken since May
14, when we upgraded our github/issue-labeler version from v2.0 to v4.1
in https://github.com/mdn/content/commit/fcaab4f

Otherwise, without this change, when github/issue-labeler v4.1+ see
slashes in the paths/slugs in our issue-regex-labeler.yml — for example,
'/docs/Web/Accessibility' — the slashes don’t get parsed as literal
slashes but instead are considered to be delimiters of the start and end
of regex patterns. And that causes a failure with:

> Error: SyntaxError: Invalid flags supplied to RegExp constructor
> 'Accessibility'