Add note about module not yet installed
Running the program exactly as-is at this point will return the following error:
Error: Cannot find module 'express-validator'
The tutorial either needs to instruct people to install express-validator or comment out the code for now.