Change arrow function in .get() to anonymous function
In the sample code we are passing in an arrow function to .get() which means we don't have access to 'this' (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Lexical_this). 

Once the user gets to this section https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/Displaying_data/Genre_detail_page they will notice that it doesn't work  because the url to book details is actually http://localhost:3000/catalog/genre/undefined. 
```
Cast to ObjectId failed for value "undefined" (type string) at path "_id" for model "genre"
CastError: Cast to ObjectId failed for value "undefined" (type string) at path "_id" for model "genre"
...
```

There is a note saying to use mongoose.Types.ObjectId() but that doesn't work because there is no id to convert.

I have updated the example to use an anonymous function instead of an arrow function so we still have access to this._id