updated `bstack_google_test.js` file
Current version on this mdn web docs page looks like it is using outdated code, found on the [Selenium WebDriver capabilities for running tests on BrowserStack.](https://www.browserstack.com/automate/capabilities?tag=selenium-4).  It produces the following error:

```js
/.../selenium-test/node_modules/selenium-webdriver/lib/http.js:618
    throw new error.WebDriverError(value)
          ^

WebDriverError: Authorization required
    at parseHttpResponse (/.../selenium-test/node_modules/selenium-webdriver/lib/http.js:618:11)
    at Executor.execute (/.../selenium-test/node_modules/selenium-webdriver/lib/http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  remoteStacktrace: ''
}
```